
extends:
  - google
  - "plugin:@typescript-eslint/recommended"
  - plugin:prettier/recommended
parser: "@typescript-eslint/parser"
parserOptions:
  sourceType: module
plugins:
  - "@typescript-eslint"

env:
  es6: true
  node: true
rules:
  prettier/prettier:
    - error
    - singleQuote: true
      trailingComma: all
  require-jsdoc: off
  "@typescript-eslint/indent": 
    - error
    - 2
  "@typescript-eslint/explicit-function-return-type":
    - error
    - allowExpressions: true
